function [H] = h(x, y, hyp,i)

global ModelInfo;
a = ModelInfo.alpha;
logsigma = hyp(1);
logtheta = hyp(2);

if i == 0
    hh = @(x,y) exp(1).^(logsigma+(-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y) ...
        .^2).*(exp(1).^((-1).*logtheta)).^(1/2).*(exp(1).^logtheta).^(( ...
        -1/2).*a).*pi.^(-1/2).*((-1).*(exp(1).^logtheta).^((1/2).*(1+a)).* ...
        pi.^(1/2)+2.^((1/2).*a).*(exp(1).^logtheta).^(1/2).*cos((1/2).*a.* ...
        pi).*gamma((1/2).*(1+a)).*kummer((-1/2).*a,(1/2),(1/2) ...
        .*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+2.^((1/2).*(1+a)).*(x+ ...
        (-1).*y).*gamma(1+(1/2).*a).*kummer((1/2).*(1+(-1).*a), ...
        (3/2),(1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2).*sin((1/2) ...
        .*a.*pi));
    
    H = bsxfun(hh,x,y');
elseif i==1
    hh = @(x,y)exp(1).^(logsigma+(-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y) ...
        .^2).*(exp(1).^((-1).*logtheta)).^(1/2).*(exp(1).^logtheta).^(( ...
        -1/2).*a).*pi.^(-1/2).*((-1).*(exp(1).^logtheta).^((1/2).*(1+a)).* ...
        pi.^(1/2)+2.^((1/2).*a).*(exp(1).^logtheta).^(1/2).*cos((1/2).*a.* ...
        pi).*gamma((1/2).*(1+a)).*kummer((-1/2).*a,(1/2),(1/2) ...
        .*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+2.^((1/2).*(1+a)).*(x+ ...
        (-1).*y).*gamma(1+(1/2).*a).*kummer((1/2).*(1+(-1).*a), ...
        (3/2),(1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2).*sin((1/2) ...
        .*a.*pi));
    
    H = bsxfun(hh,x,y');
    
elseif i==2
    hh = @(x,y) (-1/6).*exp(1).^(logsigma+(-1).*logtheta+(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2).*(exp(1).^((-1).*logtheta)).^(1/2).*( ...
        exp(1).^logtheta).^((1/2).*((-1)+(-1).*a)).*pi.^(-1/2).*(3.*(exp( ...
        1).^logtheta).^((1/2).*(2+a)).*pi.^(1/2).*(x+(-1).*y).^2+2.^((1/2) ...
        .*a).*(3.*exp(1).^logtheta.*cos((1/2).*a.*pi).*gamma((1/2).*(1+a)) ...
        .*(a.*exp(1).^logtheta.*kummer((-1/2).*a,(1/2),(1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+(-1).*(1+a).*(x+(-1).*y) ...
        .^2.*kummer((-1/2).*a,(3/2),(1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2))+2.^(1/2).*(exp(1).^logtheta).^(1/2).*( ...
        x+(-1).*y).*gamma(1+(1/2).*a).*(3.*(1+a).*exp(1).^logtheta.* ...
        kummer((1/2).*(1+(-1).*a),(3/2),(1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2)+(-1).*(2+a).*(x+(-1).*y).^2.* ...
        kummer((1/2).*(1+(-1).*a),(5/2),(1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2)).*sin((1/2).*a.*pi)));
    
    H = bsxfun(hh,x,y');
end

