function K = k(x, y, hyp,i)

global ModelInfo;
a = ModelInfo.alpha;

logsigma = hyp(1);
logtheta = hyp(2);

if i == 0
    
    kk = @(x,y) exp(1).^logsigma.*(exp(1).^((-1).*logtheta)).^(1/2).*(exp(1) ...
        .^logtheta).^(1/2).*pi.^(-1/2).*(exp(1).^((-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2).*pi.^(1/2)+2.^a.*(exp(1).^logtheta).^(( ...
        -1).*a).*gamma((1/2)+a).*kummer((1/2)+a,(1/2),(-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+(-1).*2.^(1+(1/2).*a).*( ...
        exp(1).^logtheta).^((-1/2).*a).*cos((1/2).*a.*pi).*gamma((1/2).*( ...
        1+a)).*kummer((1/2).*(1+a),(1/2),(-1/2).*exp(1).^((-1) ...
        .*logtheta).*(x+(-1).*y).^2));
    
    K = real(bsxfun(kk,x,y'));
    
elseif i == 1
    kk = @(x,y) exp(1).^logsigma.*(exp(1).^((-1).*logtheta)).^(1/2).*(exp(1) ...
        .^logtheta).^(1/2).*pi.^(-1/2).*(exp(1).^((-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2).*pi.^(1/2)+2.^a.*(exp(1).^logtheta).^(( ...
        -1).*a).*gamma((1/2)+a).*kummer((1/2)+a,(1/2),(-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+(-1).*2.^(1+(1/2).*a).*( ...
        exp(1).^logtheta).^((-1/2).*a).*cos((1/2).*a.*pi).*gamma((1/2).*( ...
        1+a)).*kummer((1/2).*(1+a),(1/2),(-1/2).*exp(1).^((-1) ...
        .*logtheta).*(x+(-1).*y).^2));
    
    K = real(bsxfun(kk,x,y'));
    
elseif i==2
    kk = @(x,y) (1/2).*exp(1).^logsigma.*(exp(1).^((-1).*logtheta)).^(1/2).*(exp( ...
        1).^logtheta).^(-1/2).*(exp(1).^((-1/2).*exp(1).^((-1).*logtheta) ...
        .*(x+(-1).*y).^2).*(x+(-1).*y).^2+2.^a.*(exp(1).^logtheta).^((-1) ...
        .*a).*pi.^(-1/2).*gamma((1/2)+a).*((-2).*a.*exp(1).^logtheta.* ...
        kummer((1/2)+a,(1/2),(-1/2).*exp(1).^((-1).*logtheta).* ...
        (x+(-1).*y).^2)+(1+2.*a).*(x+(-1).*y).^2.*kummer((3/2)+ ...
        a,(3/2),(-1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2))+2.^(1+( ...
        1/2).*a).*(exp(1).^logtheta).^((-1/2).*a).*pi.^(-1/2).*cos((1/2).* ...
        a.*pi).*gamma((1/2).*(1+a)).*(a.*exp(1).^logtheta.* ...
        kummer((1/2).*(1+a),(1/2),(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2)+(-1).*(1+a).*(x+(-1).*y).^2.* ...
        kummer((1/2).*(3+a),(3/2),(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2)));
    
    K = real(bsxfun(kk,x,y'));
    
end

