function [K] = k(x, y, hyp,i)

logsigma = hyp(1);
logtheta = hyp(2:end);

if i==0
    
    kk = @(x,y) exp(1).^(logsigma+(-1).*logtheta+(-1/2).*exp(1).^((-1).*logtheta) ...
        .*(x+(-1).*y).^2)+exp(1).^(logsigma+(1/2).*logtheta).*(exp(1).^(( ...
        -1/2).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*x.^2).*(2.*pi.^( ...
        -1)).^(1/2)+(-1).*exp(1).^((-1/2).*logtheta+(-1/2).*exp(1).^((-1) ...
        .*logtheta).*((-1).*x+y).^2).*(2.*pi.^(-1)).^(1/2)).*((1/2).*pi) ...
        .^(1/2)+(-1).*exp(1).^(logsigma+(-2).*logtheta+(-1/2).*exp(1).^(( ...
        -1).*logtheta).*(x+(-1).*y).^2).*(x+(-1).*y).^2+(1/2).*exp(1) ...
        .^logsigma.*((-2).*exp(1).^logtheta+2.*exp(1).^(logtheta+(-1/2).* ...
        exp(1).^((-1).*logtheta).*x.^2)+(-2).*exp(1).^(logtheta+(-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+(-2).*exp(1).^((-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+2.*exp(1).^((-1/2).*exp( ...
        1).^((-1).*logtheta).*y.^2)+2.*exp(1).^(logtheta+(-1/2).*exp(1).^( ...
        (-1).*logtheta).*y.^2)+exp(1).^((1/2).*logtheta).*(2.*pi).^(1/2).* ...
        x.*erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*x)+exp(1).^((1/2).* ...
        logtheta).*(2.*pi).^(1/2).*y.*erf(2.^(-1/2).*exp(1).^((-1/2).* ...
        logtheta).*y)+exp(1).^((1/2).*logtheta).*(2.*pi).^(1/2).*x.*erf( ...
        2.^(-1/2).*exp(1).^((-1/2).*logtheta).*((-1).*x+y))+(-1).*exp(1) ...
        .^((1/2).*logtheta).*(2.*pi).^(1/2).*y.*erf(2.^(-1/2).*exp(1).^(( ...
        -1/2).*logtheta).*((-1).*x+y)));
    
    K = bsxfun(kk,x,y');
    
elseif i==1
    
    kk = @(x,y) exp(1).^(logsigma+(-1).*logtheta+(-1/2).*exp(1).^((-1).*logtheta) ...
        .*(x+(-1).*y).^2)+exp(1).^(logsigma+(1/2).*logtheta).*(exp(1).^(( ...
        -1/2).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*x.^2).*(2.*pi.^( ...
        -1)).^(1/2)+(-1).*exp(1).^((-1/2).*logtheta+(-1/2).*exp(1).^((-1) ...
        .*logtheta).*((-1).*x+y).^2).*(2.*pi.^(-1)).^(1/2)).*((1/2).*pi) ...
        .^(1/2)+(-1).*exp(1).^(logsigma+(-2).*logtheta+(-1/2).*exp(1).^(( ...
        -1).*logtheta).*(x+(-1).*y).^2).*(x+(-1).*y).^2+(1/2).*exp(1) ...
        .^logsigma.*((-2).*exp(1).^logtheta+2.*exp(1).^(logtheta+(-1/2).* ...
        exp(1).^((-1).*logtheta).*x.^2)+(-2).*exp(1).^(logtheta+(-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+(-2).*exp(1).^((-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2)+2.*exp(1).^((-1/2).*exp( ...
        1).^((-1).*logtheta).*y.^2)+2.*exp(1).^(logtheta+(-1/2).*exp(1).^( ...
        (-1).*logtheta).*y.^2)+exp(1).^((1/2).*logtheta).*(2.*pi).^(1/2).* ...
        x.*erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*x)+exp(1).^((1/2).* ...
        logtheta).*(2.*pi).^(1/2).*y.*erf(2.^(-1/2).*exp(1).^((-1/2).* ...
        logtheta).*y)+exp(1).^((1/2).*logtheta).*(2.*pi).^(1/2).*x.*erf( ...
        2.^(-1/2).*exp(1).^((-1/2).*logtheta).*((-1).*x+y))+(-1).*exp(1) ...
        .^((1/2).*logtheta).*(2.*pi).^(1/2).*y.*erf(2.^(-1/2).*exp(1).^(( ...
        -1/2).*logtheta).*((-1).*x+y)));
    
    K = bsxfun(kk,x,y');
    
elseif i==2
    
    kk = @(x,y) (1/2).*exp(1).^(logsigma+(1/2).*logtheta).*(exp(1).^((-1/2).* ...
        logtheta+(-1/2).*exp(1).^((-1).*logtheta).*x.^2).*(2.*pi.^(-1)).^( ...
        1/2)+(-1).*exp(1).^((-1/2).*logtheta+(-1/2).*exp(1).^((-1).* ...
        logtheta).*((-1).*x+y).^2).*(2.*pi.^(-1)).^(1/2)).*((1/2).*pi).^( ...
        1/2)+exp(1).^(logsigma+(-1).*logtheta+(-1/2).*exp(1).^((-1).* ...
        logtheta).*(x+(-1).*y).^2).*((-1)+(1/2).*exp(1).^((-1).*logtheta) ...
        .*(x+(-1).*y).^2)+(-1).*exp(1).^(logsigma+(-2).*logtheta+(-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2).*((-2)+(1/2).*exp(1).^(( ...
        -1).*logtheta).*(x+(-1).*y).^2).*(x+(-1).*y).^2+exp(1).^(logsigma+ ...
        (1/2).*logtheta).*((1/2).*pi).^(1/2).*(exp(1).^((-1/2).*logtheta+( ...
        -1/2).*exp(1).^((-1).*logtheta).*x.^2).*(2.*pi.^(-1)).^(1/2).*(( ...
        -1/2)+(1/2).*exp(1).^((-1).*logtheta).*x.^2)+(-1).*exp(1).^((-1/2) ...
        .*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*((-1).*x+y).^2).*(2.* ...
        pi.^(-1)).^(1/2).*((-1/2)+(1/2).*exp(1).^((-1).*logtheta).*((-1).* ...
        x+y).^2))+(1/2).*exp(1).^logsigma.*((-2).*exp(1).^logtheta+(-1).* ...
        exp(1).^((-1/2).*exp(1).^((-1).*logtheta).*x.^2).*x.^2+2.*exp(1) ...
        .^(logtheta+(-1/2).*exp(1).^((-1).*logtheta).*x.^2).*(1+(1/2).* ...
        exp(1).^((-1).*logtheta).*x.^2)+(-2).*exp(1).^(logtheta+(-1/2).* ...
        exp(1).^((-1).*logtheta).*(x+(-1).*y).^2).*(1+(1/2).*exp(1).^((-1) ...
        .*logtheta).*(x+(-1).*y).^2)+(-1).*exp(1).^((-1).*logtheta+(-1/2) ...
        .*exp(1).^((-1).*logtheta).*(x+(-1).*y).^2).*(x+(-1).*y).^2+(-1).* ...
        exp(1).^((-1/2).*exp(1).^((-1).*logtheta).*y.^2).*y.^2+exp(1).^(( ...
        -1).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*y.^2).*y.^2+(-1).* ...
        exp(1).^((-1/2).*exp(1).^((-1).*logtheta).*((-1).*x+y).^2).*x.*(( ...
        -1).*x+y)+exp(1).^((-1/2).*exp(1).^((-1).*logtheta).*((-1).*x+y) ...
        .^2).*y.*((-1).*x+y)+2.*exp(1).^(logtheta+(-1/2).*exp(1).^((-1).* ...
        logtheta).*y.^2).*(1+(1/2).*exp(1).^((-1).*logtheta).*y.^2)+exp(1) ...
        .^((1/2).*logtheta).*((1/2).*pi).^(1/2).*x.*erf(2.^(-1/2).*exp(1) ...
        .^((-1/2).*logtheta).*x)+exp(1).^((1/2).*logtheta).*((1/2).*pi).^( ...
        1/2).*y.*erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*y)+exp(1).^(( ...
        1/2).*logtheta).*((1/2).*pi).^(1/2).*x.*erf(2.^(-1/2).*exp(1).^(( ...
        -1/2).*logtheta).*((-1).*x+y))+(-1).*exp(1).^((1/2).*logtheta).*(( ...
        1/2).*pi).^(1/2).*y.*erf(2.^(-1/2).*exp(1).^((-1/2).*logtheta).*(( ...
        -1).*x+y)));
    
    K = bsxfun(kk,x,y');
    
end

end

